### ISSUE TITLE
Shell script for Linux does not seem to exist

### ISSUE THREAD

**Issue by presentformyfriends** [locaal-ai/obs-backgroundremoval#593]
**Describe the bug**

`/.github/scripts/build-linux.sh` script does not seem to exist.

**To Reproduce**

1. Follow README steps for building the plugin for Linux
2. Clone the repo
3. The only build step is "Use the CI scripts again" (no idea why it says 'again' since this is the only step)
4. Run the corresponding command for the one build step:
`$ ./.github/scripts/build-linux.sh`

**Expected behavior**

I expect the command to start building the plugin. Instead I get the following error:
`bash: ./.github/scripts/build-linux.sh: No such file or directory`

**Desktop (please complete the following information):**

 - OS: Linux Mint 21.3 (Virginia)
 - Browser: N/A
 - Plugin Version: 1.2.0
 - OBS Version: 30.2.2

**Comment by umireon** [comment]
Can you write build instructions for Mint and open a pull request to add this?
