### ISSUE TITLE
Package manager usage

### ISSUE THREAD

**Issue by Pylou-AI** [locaal-ai/obs-backgroundremoval#600]
**Is your feature request related to a problem? Please describe.**

Yes it is: deb package manager is intended for Debian and Debian-descendant distro, with upward compatibility in mind!

**Describe the solution you'd like**

NOT having a **deb** package that **won't** work on Debian!

**Describe alternatives you've considered**

Use a distro-specific package manager: Snap for Ubuntu-based distro, for instance!

**Additional context**

There's a deb file here with something that will **not** work on Debian...

**Comment by umireon** [comment]
OBS official recommends to use deb package for OBS plugin so we have nothing to do with your opinion

**Comment by umireon** [comment]
You may want to say this for [upstream](https://github.com/obsproject/obs-plugintemplate). Not for us.

**Comment by Pylou-AI** [comment]
OB officials say (from your own link):

[> On Linux, the version used for development might be decided by the **specific version available** via a **distribution's package management system**, so OBS Studio compatibility for plugins might be determined by those versions instead.](https://github.com/obsproject/obs-plugintemplate#:~:text=On%20Linux%2C%20the%20version%20used%20for%20development%20might%20be%20decided%20by%20the%20specific%20version%20available%20via%20a%20distribution%27s%20package%20management%20system%2C%20so%20OBS%20Studio%20compatibility%20for%20plugins%20might%20be%20determined%20by%20those%20versions%20instead.)

And

> [Linux dependencies need to be resolved using the package management tools **appropriate for the local distribution**.](https://github.com/obsproject/obs-plugintemplate#:~:text=Linux%20dependencies%20need%20to%20be%20resolved%20using%20the%20package%20management%20tools%20appropriate%20for%20the%20local%20distribution.)

If a package is only supporting Ubuntu, it should be delivered through Snap, not deb.

I understand you guys don't like that and that it might require some change, but that's not MY opinion.
That's good practice.

**Comment by umireon** [comment]
You can provide us the Snap implementation via your PR. Thank for considering contribution!
